name: Addons
version: ${project.version}
main: xyz.destiall.addons.Addons
softdepend:  [ KitBattle, WorldGuard, HolographicDisplays, CMI ]
authors: [ destiall ]
description: For SGC
website: https://www.destial.xyz
api-version: 1.13
commands:
  addons:
    description: Addons command
